- functions/api/routes/user/index.js
- functions/api/routes/user/keywordCreatePOST.js
- functions/constants/responseMessage.js
- functions/db/index.js
- functions/db/keywordDB.js
> [feat] 키워드 생성 

- functions/api/routes/team/index.js
- functions/api/routes/team/teamIssueCategoryGET.js
- functions/api/routes/team/teamIssuePOST.js
- functions/constants/responseMessage.js
- functions/db/issueDB.js
> [feat] 팀 이슈 카테고리 조회 및 새로운 이슈 생성

- functions/api/routes/user/index.js
- functions/api/routes/user/userSearchGET.js
- functions/constants/responseMessage.js
- functions/db/userDB.js
#18
statusCode 204를 보내면 response로 아무것도 돌아오지 않는다
> [feat] profileId로 user 검색 구현

- functions/api/routes/team/index.js
- functions/api/routes/team/teamMemberListGET.js
- functions/api/routes/user/index.js
- functions/api/routes/user/keywordListGET.js
- functions/constants/responseMessage.js
- functions/db/keywordDB.js
- functions/db/memberDB.js
- functions/middlewares/slackAPI.js
> [feat] slack Webhook 세팅

- functions/api/routes/team/index.js
- functions/api/routes/team/teamInviteGET.js
- functions/api/routes/team/teamInvitePOST.js
- functions/db/memberDB.js
- functions/db/teamDB.js
> [feat] 팀 초대 수락

- functions/api/routes/team/index.js
- functions/api/routes/team/teamFeedbackCreatePOST.js
- functions/api/routes/team/teamMemberListGET.js
- functions/api/routes/user/keywordCreatePOST.js
- functions/api/routes/user/keywordListGET.js
- functions/constants/responseMessage.js
- functions/db/feedbackDB.js
- functions/db/index.js
- functions/db/keywordDB.js
- functions/db/linkFeedbacKeywordDB
> [feat] 피드백 생성 작업중

- functions/api/routes/team/teamDetailIssueGET.js
- functions/api/routes/team/teamIssueGET.js
- functions/db/issueDB.js
> [chore] 최신순 정렬 구현 완료

- functions/api/routes/team/teamFeedbackCreatePOST.js
- functions/api/routes/user/keywordCreatePOST.js
- functions/db/keywordDB.js
- functions/db/linkFeedbacKeywordDB.js
> [feat] 피드백 생성 완료 #19

- functions/api/routes/form/formTemplatePopularGET.js
- functions/api/routes/form/formTemplateRecentGET.js
- functions/api/routes/form/index.js
- functions/api/routes/index.js
- functions/api/routes/team/teamDetailIssueGET.js
- functions/api/routes/team/teamIssueGET.js
- functions/constants/responseMessage.js
- functions/db/formDB.js
- functions/db/index.js
- functions/db/issueDB.js
> [feat] form 정보 전체 조회

- functions/api/routes/team/index.js
- functions/api/routes/team/teamPUT.js
- functions/api/routes/user/userSearchGET.js
- functions/constants/responseMessage.js
- functions/db/memberDB.js
- functions/db/teamDB.js
- functions/db/userDB.js
> [feat] 팀 정보 수정, 팀원 추가

- functions/api/routes/team/teamIssuePOST.js
- functions/db/memberDB.js
> [add] 팀의 멤버인지 확인하는 코드 추가

- functions/api/routes/form/formCreateGET.js
- functions/api/routes/form/index.js
- functions/api/routes/team/teamDetailGET.js
- functions/api/routes/team/teamDetailIssueGET.js
- functions/api/routes/team/teamDetailMyIssueGET.js
- functions/api/routes/team/teamIssueGET.js
- functions/constants/responseMessage.js
- functions/db/formDB.js
- functions/db/teamDB.js
> [fix] 오류 수정

- functions/api/routes/auth/authRegisterPOST.js
> [feat] 배포를 위한 머지

- functions/api/routes/form/formCreateGET.js
- functions/api/routes/form/formTemplatePopularGET.js
- functions/api/routes/form/formTemplateRecentGET.js
- functions/api/routes/team/teamDetailGET.js
- functions/api/routes/team/teamDetailIssueGET.js
- functions/api/routes/team/teamDetailMyIssueGET.js
- functions/api/routes/team/teamGET.js
- functions/api/routes/team/teamIssueGET.js
- functions/db/formDB.js
- functions/db/issueDB.js
- functions/middlewares/crypto.js
- functions/middlewares/resizeImage.js
> [feat] 이미지, 링크

- functions/api/routes/user/index.js
- functions/api/routes/user/userInformationByTokenGET.js
- functions/db/userDB.js
> [feat] 토큰으로 접속 유저 정보 가져오기

- functions/api/routes/team/index.js
- functions/api/routes/team/teamIssueDetailFeedbackGET.js
- functions/api/routes/team/teamIssueDetailFeedbackPinPUT.js
- functions/api/routes/team/teamIssueDetailGET.js
- functions/api/routes/user/keywordListGET.js
- functions/constants/responseMessage.js
- functions/db/feedbackDB.js
- functions/db/keywordDB.js
- functions/db/linkFeedbacKeywordDB.js
- functions/lib/arrayHandler.js
> [feat] 팀 이슈 디테일 피드백 조회, 핀 토글 작업 완료

- functions/api/routes/form/formAnswerGET.js
> [chore] 복호화 수정 #53

- functions/api/routes/form/formCreatePOST.js
- functions/api/routes/form/index.js
> [chore] method 변경 #62

- functions/api/routes/team/teamPOST.js
- functions/api/routes/user/userSearchGET.js
- functions/db/memberDB.js
- functions/db/teamDB.js
- functions/db/userDB.js
> [fix] teamPOST,userSearchGET 서버 내부 에러 수정

- functions/api/routes/team/index.js
- functions/api/routes/team/teamIssueDetailGET.js
- functions/constants/responseMessage.js
- functions/db/issueDB.js
- functions/db/linkFeedbacKeywordDB.js
- functions/db/teamDB.js
- functions/package-lock.json
> [feat] 팀 이슈 디테일 조회

- functions/api/routes/auth/authLoginPOST.js
- functions/api/routes/form/formBannerGET.js
- functions/api/routes/form/index.js
- functions/constants/responseMessage.js
- functions/db/formDB.js
> [feat] 너소서 배너 조회

- functions/api/routes/form/formAnswerCreatePOST.js
- functions/api/routes/form/index.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/linkAnswerKeywordDB.js
> [feat] 너가소개서 답변 생성

- functions/api/routes/form/formAnswerCreatePOST.js
- functions/api/routes/form/index.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/linkAnswerKeywordDB.js
- functions/db/userDB.js
#72
쿼리문에서 파라미터를 넣는 방법에 따라 쿼리문 출력 방식이 조금씩 달라짐
profileIdSet = ('mimi')
$1 => "('mimi')"
${profileIdSet} => ('mimi')
> [add] ILIKE문 추가를 통해 profileId의 일부만 입력해도 검색 가능

- functions/api/routes/form/formDetailAnswerGET.js
- functions/api/routes/form/formDetailGET.js
- functions/api/routes/form/index.js
- functions/api/routes/team/teamIssueDetailFeedbackGET.js
- functions/api/routes/team/teamMemberListGET.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/formDB.js
- functions/db/keywordDB.js
> [feat] 너소서 폼 디테일 

- functions/api/routes/auth/authLoginPOST.js
- functions/api/routes/form/formCreatePOST.js
- functions/api/routes/form/formMyGET.js
- functions/api/routes/form/formMyNewGET.js
- functions/api/routes/form/index.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/formDB.js
- functions/db/keywordDB.js
> [feat] 내가 생성한 너가소개서 조회

- functions/api/routes/form/formDetailAnswerGET.js
- functions/db/answerDB.js
- functions/db/keywordDB.js
- functions/package-lock.json
> [feat] 키워드 생성 아이디 값 리턴 

- functions/api/routes/user/index.js
> [feat] 서진이가 요청한, checkUser 빼주기

- functions/api/routes/user/index.js
- functions/api/routes/user/keywordCreatePOST.js
- functions/api/routes/user/keywordListGET.js
> [feat] 키워드 리스트 조회, 생성 checkUser 미들웨어 삭제

- functions/api/routes/team/teamIssuePOST.js
- functions/db/memberDB.js
> [fix] 이슈 생성 오류 수정

- functions/api/routes/form/formDetailAnswerGET.js
- functions/api/routes/team/teamIssueDetailFeedbackGET.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/linkAnswerKeywordDB.js
- functions/db/linkFeedbacKeywordDB.js
> [feat] 너소서 폼 이슈 디테일 작업 완료

- functions/api/routes/form/formMyGET.js
> [chore] 생성한 폼이 한개인 경우

- functions/api/routes/team/teamFeedbackCreatePOST.js
- functions/db/answerDB.js
- functions/db/userDB.js
> [feat] 자잘한 수정들

- functions/db/answerDB.js
> [chore] answerDB 쿼리문 재수정

- functions/api/routes/team/teamIssuePOST.js
> [chore] 이슈 생성 메소드 파라미터 순서 변경

- functions/api/routes/form/formCreatePOST.js
> [feat] 생성한 적 있는 폼일 때

- functions/api/routes/form/formDetailAnswerPinPUT.js
- functions/api/routes/form/index.js
- functions/api/routes/team/teamIssueDetailFeedbackPinPUT.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
> [feat] 답변 핀 토글

- functions/api/routes/user/userInformationByProfileIdGET.js
- functions/db/answerDB.js
- functions/db/linkAnswerKeywordDB.js
- functions/db/linkFeedbacKeywordDB.js
- functions/db/userDB.js
> [feat] 유저 키워드 조회 구현 완료

- functions/db/keywordDB.js
> [feat] topKeyword 쿼리 수정

- functions/api/routes/user/keywordCreatePOST.js
- functions/db/keywordDB.js
> [fix] 키워드 생성 수정

- functions/api/routes/team/teamIssueDetailFeedbackGET.js
- functions/constants/responseMessage.js
> [fix] issue/:issueId/feedback 피드백 없는 경우 분기처리

- functions/api/routes/form/formMyGET.js
> [chore] 답변 없는 폼

- functions/api/routes/auth/authLoginPOST.js
- functions/api/routes/auth/authRegisterPOST.js
- functions/api/routes/form/formDetailGET.js
- functions/api/routes/form/formMyGET.js
- functions/api/routes/form/formMyNewGET.js
- functions/api/routes/team/teamDetailGET.js
- functions/api/routes/team/teamDetailIssueGET.js
- functions/api/routes/team/teamDetailMyIssueGET.js
- functions/api/routes/team/teamGET.js
- functions/api/routes/team/teamInviteAcceptPUT.js
- functions/api/routes/team/teamInviteGET.js
- functions/api/routes/team/teamInviteRejectPUT.js
- functions/api/routes/team/teamIssueCategoryGET.js
- functions/api/routes/team/teamIssueDetailFeedbackGET.js
- functions/api/routes/team/teamIssueGET.js
- functions/api/routes/team/teamIssuePOST.js
- functions/api/routes/team/teamPOST.js
- functions/api/routes/team/teamPUT.js
- functions/api/routes/user/keywordCreatePOST.js
- functions/api/routes/user/keywordListGET.js
- functions/api/routes/user/userSearchGET.js
> [fix] url 변경으로 폼 정보 조회

- functions/db/answerDB.js
> [chore] 너소서 폼 최신순

- functions/api/routes/auth/index.js
- functions/api/routes/team/index.js
- functions/middlewares/uploadImage.js
- close #105 
https://dev-dorydory.tistory.com/6
> [feat] 파이어베이스 스토리지 폴더링 

- functions/api/routes/form/formMyGET.js
- functions/api/routes/form/formMyNewGET.js
답변이 달린 폼이 하나도 없을 때 / 있을 때 형태 통일
#108
> [refactor] 리스폰스 뎁쓰 통일

- functions/api/routes/form/formMyGET.js
- functions/api/routes/form/formMyMostGET.js
- functions/api/routes/form/formMyNewGET.js
- functions/api/routes/form/index.js
- functions/db/answerDB.js
> [feat] 내가 생성한 너가소개서 전체 조회

- functions/api/routes/team/teamDetailIssueGET.js
- functions/api/routes/team/teamDetailMyIssueGET.js
- functions/api/routes/team/teamIssueGET.js
- functions/db/issueDB.js
- functions/package-lock.json
> [refactor] 팀소서 이슈 조회 리스폰스 수정

- functions/api/routes/user/userPinnedTeamGET.js
- functions/constants/responseMessage.js
- functions/db/teamDB.js
> [refactor] 마이페이지 조회 리스폰스 수정

- functions/db/teamDB.js
> [chore] 팀 정보 조회 리스폰스 수정

- functions/db/teamDB.js
> [chore] 기획 변동사항

- functions/api/routes/team/index.js
- functions/api/routes/team/teamDELETE.js
- functions/api/routes/team/teamHostPUT.js
- functions/api/routes/team/teamMemberDELETE.js
- functions/constants/responseMessage.js
- functions/db/memberDB.js
- functions/db/teamDB.js
> [feat] 팀소서 미트볼

- functions/api/routes/form/formCreatePOST.js
- functions/db/answerDB.js
- functions/db/formDB.js
> [chore] light_icon_image 컬럼 삭제로 인한 변수명 변경

- functions/api/routes/user/index.js
- functions/api/routes/user/keywordCreatePOST.js
- functions/api/routes/user/keywordDELETE.js
- functions/api/routes/user/keywordListGET.js
- functions/constants/responseMessage.js
- functions/db/keywordDB.js
> [fix] 전반적인 키워드 로직 수정

- functions/api/routes/user/index.js
- functions/api/routes/user/keywordCreatePOST.js
- functions/api/routes/user/keywordDELETE.js
- functions/api/routes/user/myKeywordDELETE.js
- functions/api/routes/user/myKeywordListGet.js
- functions/constants/responseMessage.js
- functions/db/keywordDB.js
> [feat] 마이키워드 조회/ 삭제

- functions/api/routes/team/index.js
- functions/api/routes/team/teamMemberEditGET.js
- functions/api/routes/team/teamMemberEditPOST.js
- functions/api/routes/team/teamPUT.js
- functions/api/routes/user/userSearchGET.js
> [chore] 팀원 관리 수정

- functions/api/routes/team/teamDetailGET.js
> [add] 404 처리

- functions/api/routes/user/index.js
- functions/api/routes/user/userDELETE.js
- functions/constants/responseMessage.js
- functions/db/userDB.js
> [feat] 회원 탈퇴

- functions/api/routes/user/userSearchGET.js
> [chore] 쿼리 파라미터 변경

- functions/api/routes/form/formDetailAnswerGET.js
- functions/api/routes/form/formDetailGET.js
- functions/api/routes/team/teamIssueDetailFeedbackGET.js
- functions/api/routes/team/teamIssueDetailGET.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/keywordDB.js
- functions/db/linkAnswerKeywordDB.js
- functions/db/linkFeedbacKeywordDB.js
> [fix] 팀 이슈 디테일 / 너소서 폼 디테일 수정

- functions/api/routes/form/formAnswerDELETE.js
- functions/api/routes/form/index.js
- functions/api/routes/team/index.js
- functions/api/routes/team/teamFeedbackCreatePOST.js
- functions/api/routes/team/teamFeedbackDELETE.js
- functions/api/routes/team/teamFeedbackPUT.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/feedbackDB.js
- functions/db/keywordDB.js
- functions/db/linkAnswerKeywordDB.js
- functions/db/linkFeedbacKeywordDB.js
> [feat] 피드백 수정/삭제, 폼 답변 삭제

- functions/api/routes/user/index.js
> [fix] 빠진 미들웨어 추가

- functions/api/routes/form/formAnswerDELETE.js
- functions/constants/responseMessage.js
> [fix] 답변 삭제/ 피드백 삭제 리스폰스 메시지 수정

- functions/api/routes/form/formAnswerPickGET.js
- functions/api/routes/form/index.js
- functions/api/routes/team/index.js
- functions/api/routes/team/teamFeedbackPickGET.js
- functions/constants/responseMessage.js
- functions/db/answerDB.js
- functions/db/feedbackDB.js
- functions/db/formDB.js
- functions/db/keywordDB.js
- functions/db/teamDB.js
> [feat] 마이페이지 픽하기 필터링

- functions/api/routes/form/formMyGET.js
- functions/api/routes/form/formMyMostGET.js
- functions/api/routes/form/formMyNewGET.js
- functions/db/formDB.js
- functions/db/keywordDB.js
/form, /form/new, /form/most
#156
> [chore] 기획/디자인 변동사항 수정

- functions/db/feedbackDB.js
- functions/db/keywordDB.js
> [chore] 마이페이지 픽하기 자잘한 수정

- functions/api/routes/team/index.js
- functions/api/routes/team/teamIssueDELETE.js
- functions/api/routes/team/teamIssuePUT.js
- functions/constants/responseMessage.js
- functions/db/issueDB.js
#143 
이미지 수정의 put api 모두 수정해야함
> [feat] 이슈 미트볼 수정 및 삭제

- functions/api/routes/form/formAnswerGET.js
- functions/db/answerDB.js
- functions/db/feedbackDB.js
- functions/db/formDB.js
- functions/db/keywordDB.js
> [refactor] 폼 정보 받아오기 리팩토링 및 리스폰스 데이터 추가

- functions/api/routes/team/teamDetailMyIssueGET.js
> [chore] 팀의 이슈 확인

- functions/api/routes/form/formDetailAnswerGET.js
- functions/api/routes/team/teamIssueDetailGET.js
- functions/db/issueDB.js
- functions/db/linkAnswerKeywordDB.js
> [fix] 클라이언트 요청 사항 업데이트

- functions/api/routes/user/userInformationByProfileIdGET.js
- functions/db/linkAnswerKeywordDB.js
- functions/db/linkFeedbacKeywordDB.js
> [chore] 마이페이지 리스폰스 데이터 수정

- functions/api/routes/team/index.js
- functions/api/routes/team/teamEditPUT.js
- functions/api/routes/team/teamIssuePUT.js
- functions/api/routes/user/userProfileEditPUT.js
- functions/constants/responseMessage.js
- functions/db/issueDB.js
- functions/db/teamDB.js
- functions/db/userDB.js
> [fix]수정 api 이미지 수정 버그 fix

- functions/api/routes/team/teamIssueDELETE.js
- functions/api/routes/team/teamIssuePUT.js
- functions/constants/responseMessage.js
> [chore] 이슈 미트볼 에러 로직 수정

- functions/api/routes/team/teamDetailGET.js
- functions/db/memberDB.js
- functions/db/teamDB.js
> [chore] 초대중인 멤버 제외

- functions/api/routes/team/teamDELETE.js
- functions/api/routes/team/teamHostPUT.js
- functions/api/routes/team/teamInviteAcceptPUT.js
- functions/api/routes/team/teamInviteRejectPUT.js
- functions/api/routes/team/teamMemberDELETE.js
- functions/constants/responseMessage.js
- functions/db/feedbackDB.js
- functions/db/teamDB.js
> [chore] 수정사항 반영

- functions/db/userDB.js
> [fix] 이미지 없을 때 500 에러 수정

- functions/db/userDB.js
> [fix] 유저 검색 일부 유저 누락 오류 수정

- functions/.prettierrc.js
- functions/api/routes/form/formDetailAnswerGET.js
- functions/api/routes/index.js
- functions/api/routes/report/index.js
- functions/api/routes/report/reportCategoryGET.js
- functions/api/routes/report/reportPOST.js
- functions/constants/responseMessage.js
- functions/db/index.js
- functions/db/reportDB.js
> [feat] 문의하기 관련 api 완성

- functions/api/routes/team/teamFeedbackDELETE.js
- functions/api/routes/team/teamFeedbackPUT.js
> [fix] 피드백 수정/삭제 리스폰스 코드 수정

- functions/api/routes/team/teamEditPUT.js
> [fix] 리퀘스트 빈문자열 오류 수정

- functions/api/routes/team/teamEditPUT.js
- functions/api/routes/user/userIdDuplicateCheckGET.js
> [chore] 중복검사 통과 로직 추가

- functions/api/routes/team/teamDetailGET.js
- functions/api/routes/team/teamDetailIssueGET.js
- functions/api/routes/team/teamDetailMyIssueGET.js
- functions/api/routes/team/teamFeedbackCreatePOST.js
- functions/api/routes/team/teamIssueDetailFeedbackGET.js
- functions/api/routes/team/teamIssueDetailFeedbackPinPUT.js
- functions/api/routes/team/teamIssueDetailGET.js
- functions/api/routes/team/teamIssueGET.js
- functions/api/routes/team/teamMemberListGET.js
- functions/db/issueDB.js
- functions/db/memberDB.js
#183
제가 짜지 않은 코드들도 최대한 신중하게 에러 처리 해봤으나, 이번 PR은 꼼꼼히 확인해주시길 부탁드립니다..! 🙏
> [add] 에러 처리 추가

- functions/db/formDB.js
> [chore] 폼 하나만 반환하도록 수정

- functions/db/memberDB.js
> [fix] 쿼리문 팀장 여부 select 추가

- functions/api/routes/report/reportPOST.js
- functions/db/reportDB.js
> [fix] 문의하기 이메일 추가 #199

- functions/api/routes/auth/authLoginPOST.js
- functions/api/routes/auth/authRefreshPUT.js
- functions/api/routes/auth/authRegisterPOST.js
- functions/api/routes/auth/index.js
- functions/constants/responseMessage.js
> [refactor] 카카오 소셜 로그인

- functions/db/feedbackDB.js
> [add] 이슈 캥거루에 필요한 리스폰스값 추가

- functions/api/routes/team/teamMemberListGET.js
- functions/api/routes/user/userDELETE.js
- functions/db/answerDB.js
- functions/db/feedbackDB.js
- functions/db/issueDB.js
- functions/db/linkAnswerKeywordDB.js
- functions/db/memberDB.js
- functions/db/reportDB.js
- functions/middlewares/uploadImage.js
- functions/package-lock.json
- functions/package.json
--- 
아래의 내용들을 차례로 처리한다
1. 팀 멤버 삭제
- 해당 유저가 포함된 팀에서 멤버 삭제. 
- 해당 유저가 쓴 피드백/ 포함 된 피드백 삭제. 
- 해당 피드백에 포함된 키워드들 삭제(link 테이블, 키워드 테이블에서 삭제). 
2. 이슈 삭제
- 해당 유저가 작성한 이슈 전부 삭제, 
- 해당 이슈에 연관 피드백 전부 삭제, 
- 해당 피드백에 포함된 키워드들도 삭제(link 테이블에서만 삭제 + count --해줘야함), 
3.  너소서 폼 삭제. 
- 링크 폼 유저 테이블에서 해당 유저 정보 전부 삭제, 
- 해당 유저가 받은 답변 전부 삭제, 키워드 삭제(link 테이블, 키워드 테이블에서 삭제)
4. 해당 유저를 delete 처리
--- 
close #214
> [fix] 유저 탈퇴 로직

- functions/db/formDB.js
> hotfix: fontCode로 colorCode 변경
